### ISSUE TITLE
Plans to publish to RubyGems.org?

### ISSUE THREAD

**Issue by dshorthouse** [SpeciesFileGroup/bananomia#1]
Wondering if you might contribute this to rubygems.org. Looks like a clean way to access the API responses & would like to give it a whirl.

**Comment by gdower** [comment]
Thanks for your interest, @dshorthouse! I updated the library to run on Ruby 3.2.2 and published it to RubyGems as bananomia which keeps it in the spirit of fruit/veggie puns for Ruby biodiversity informatics API wrappers. Please let me know if you have any questions or suggestions for improvement.

**Comment by dshorthouse** [comment]
🍌 Bananomia!
